set number
set relativenumber
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set wrap
set smartindent
set history=500
set undofile
set nohlsearch
set incsearch
set scrolloff=8
set updatetime=50
set colorcolumn=80
set signcolumn=yes
set termguicolors

syntax enable
colorscheme slate
