set number
set relativenumber
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set wrap
set smartindent
set history=500
set undofile
set nohlsearch
set incsearch
set scrolloff=5
set updatetime=50
set signcolumn=yes
set termguicolors
set showcmd

let mapleader=" "
nnoremap <leader>e :Ex<Enter>
nnoremap <C-j> :tabp<Enter>
nnoremap <C-k> :tabn<Enter>
nnoremap <C-t> :tabnew<Enter>
inoremap <C-c> <Esc>

syntax enable
colorscheme habamax
