set nu
set rnu

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smartindent

set wrap
set linebreak

set noswapfile
set nobackup

set undofile
set undodir=~/.vim/undodir
if !isdirectory(expand("~/.vim/undodir"))
    call mkdir(expand("~/.vim/undodir"), "p")
endif

set nohlsearch
set incsearch

set termguicolors
set signcolumn=yes

set scrolloff=5
set updatetime=50
set showcmd
set autoread

let mapleader=" "

nnoremap <leader>e :Ex<Enter>
nnoremap <C-j> :tabp<Enter>
nnoremap <C-k> :tabn<Enter>
nnoremap <C-t> :tabnew<Enter>
inoremap <C-c> <Esc>

syntax enable
colorscheme habamax
